### ISSUE TITLE
Packages miss systemd-rpm-macros build requires

### ISSUE THREAD

**Issue by Rudd-O** [lest/prometheus-rpm#560] opened 2021-12-16 14:46 UTC
As a consequence the scriptlets look like this( *actually in the system, installed*) and they don't work:

```
[root@katrina fedora]# rpm -q node_exporter --scripts
preinstall scriptlet (using /bin/sh):
getent group prometheus >/dev/null || groupadd -r prometheus
getent passwd prometheus >/dev/null || \
  useradd -r -g prometheus -d /var/lib/prometheus -s /sbin/nologin \
          -c "Prometheus services" prometheus
exit 0
postinstall scriptlet (using /bin/sh):
%systemd_post node_exporter.service
preuninstall scriptlet (using /bin/sh):
%systemd_preun node_exporter.service
postuninstall scriptlet (using /bin/sh):
%systemd_postun node_exporter.service
```

**Comment by Rudd-O** [comment] 2021-12-16 14:46
Those % should render to something, but that requires systemd-rpm-macros in the buildrequires.

**Comment by karlism** [comment] 2021-12-16 14:51
@Rudd-O, is this dependency same for RHEL 6/7/8?

**Comment by britcey** [comment] 2021-12-16 15:11
Not seeing that on freshly downloaded Centos 7 & Centos 8 images & freshly built packages[1].

Where is the package from, the repo?  Which exact package version?

[1]

```
[vagrant@localhost vagrant]$ sudo rpm -q node_exporter --scripts
preinstall scriptlet (using /bin/sh):
getent group prometheus >/dev/null || groupadd -r prometheus
getent passwd prometheus >/dev/null || \
  useradd -r -g prometheus -d /var/lib/prometheus -s /sbin/nologin \
          -c "Prometheus services" prometheus
exit 0
postinstall scriptlet (using /bin/sh):

if [ $1 -eq 1 ] ; then
        # Initial installation
        systemctl preset node_exporter.service >/dev/null 2>&1 || :
fi
preuninstall scriptlet (using /bin/sh):

if [ $1 -eq 0 ] ; then
        # Package removal, not upgrade
        systemctl --no-reload disable node_exporter.service > /dev/null 2>&1 || :
        systemctl stop node_exporter.service > /dev/null 2>&1 || :
fi
postuninstall scriptlet (using /bin/sh):

systemctl daemon-reload >/dev/null 2>&1 || :
```

**Comment by karlism** [comment] 2021-12-16 16:38
Duplicate of https://github.com/lest/prometheus-rpm/issues/294

**Closed** 2021-12-30 08:45 UTC
